// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authn.proto

package grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SignupRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *SignupRequest) Reset()      { *m = SignupRequest{} }
func (*SignupRequest) ProtoMessage() {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{0}
}
func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupResponse struct {
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token"`
}

func (m *SignupResponse) Reset()      { *m = SignupResponse{} }
func (*SignupResponse) ProtoMessage() {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{1}
}
func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type IsUsernameAvailableRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *IsUsernameAvailableRequest) Reset()      { *m = IsUsernameAvailableRequest{} }
func (*IsUsernameAvailableRequest) ProtoMessage() {}
func (*IsUsernameAvailableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{2}
}
func (m *IsUsernameAvailableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsUsernameAvailableRequest.Unmarshal(m, b)
}
func (m *IsUsernameAvailableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsUsernameAvailableRequest.Marshal(b, m, deterministic)
}
func (m *IsUsernameAvailableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsUsernameAvailableRequest.Merge(m, src)
}
func (m *IsUsernameAvailableRequest) XXX_Size() int {
	return xxx_messageInfo_IsUsernameAvailableRequest.Size(m)
}
func (m *IsUsernameAvailableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsUsernameAvailableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsUsernameAvailableRequest proto.InternalMessageInfo

func (m *IsUsernameAvailableRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type IsUsernameAvailableResponse struct {
	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result"`
}

func (m *IsUsernameAvailableResponse) Reset()      { *m = IsUsernameAvailableResponse{} }
func (*IsUsernameAvailableResponse) ProtoMessage() {}
func (*IsUsernameAvailableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{3}
}
func (m *IsUsernameAvailableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsUsernameAvailableResponse.Unmarshal(m, b)
}
func (m *IsUsernameAvailableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsUsernameAvailableResponse.Marshal(b, m, deterministic)
}
func (m *IsUsernameAvailableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsUsernameAvailableResponse.Merge(m, src)
}
func (m *IsUsernameAvailableResponse) XXX_Size() int {
	return xxx_messageInfo_IsUsernameAvailableResponse.Size(m)
}
func (m *IsUsernameAvailableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsUsernameAvailableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsUsernameAvailableResponse proto.InternalMessageInfo

func (m *IsUsernameAvailableResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type PasswordResetRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *PasswordResetRequest) Reset()      { *m = PasswordResetRequest{} }
func (*PasswordResetRequest) ProtoMessage() {}
func (*PasswordResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{4}
}
func (m *PasswordResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetRequest.Unmarshal(m, b)
}
func (m *PasswordResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetRequest.Marshal(b, m, deterministic)
}
func (m *PasswordResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetRequest.Merge(m, src)
}
func (m *PasswordResetRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordResetRequest.Size(m)
}
func (m *PasswordResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetRequest proto.InternalMessageInfo

func (m *PasswordResetRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type PasswordResetResponse struct {
}

func (m *PasswordResetResponse) Reset()      { *m = PasswordResetResponse{} }
func (*PasswordResetResponse) ProtoMessage() {}
func (*PasswordResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{5}
}
func (m *PasswordResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetResponse.Unmarshal(m, b)
}
func (m *PasswordResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetResponse.Marshal(b, m, deterministic)
}
func (m *PasswordResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetResponse.Merge(m, src)
}
func (m *PasswordResetResponse) XXX_Size() int {
	return xxx_messageInfo_PasswordResetResponse.Size(m)
}
func (m *PasswordResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetResponse proto.InternalMessageInfo

type RequestPasswordlessLoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *RequestPasswordlessLoginRequest) Reset()      { *m = RequestPasswordlessLoginRequest{} }
func (*RequestPasswordlessLoginRequest) ProtoMessage() {}
func (*RequestPasswordlessLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{6}
}
func (m *RequestPasswordlessLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPasswordlessLoginRequest.Unmarshal(m, b)
}
func (m *RequestPasswordlessLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPasswordlessLoginRequest.Marshal(b, m, deterministic)
}
func (m *RequestPasswordlessLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPasswordlessLoginRequest.Merge(m, src)
}
func (m *RequestPasswordlessLoginRequest) XXX_Size() int {
	return xxx_messageInfo_RequestPasswordlessLoginRequest.Size(m)
}
func (m *RequestPasswordlessLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPasswordlessLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPasswordlessLoginRequest proto.InternalMessageInfo

func (m *RequestPasswordlessLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RequestPasswordlessLoginResponse struct {
}

func (m *RequestPasswordlessLoginResponse) Reset()      { *m = RequestPasswordlessLoginResponse{} }
func (*RequestPasswordlessLoginResponse) ProtoMessage() {}
func (*RequestPasswordlessLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{7}
}
func (m *RequestPasswordlessLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPasswordlessLoginResponse.Unmarshal(m, b)
}
func (m *RequestPasswordlessLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPasswordlessLoginResponse.Marshal(b, m, deterministic)
}
func (m *RequestPasswordlessLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPasswordlessLoginResponse.Merge(m, src)
}
func (m *RequestPasswordlessLoginResponse) XXX_Size() int {
	return xxx_messageInfo_RequestPasswordlessLoginResponse.Size(m)
}
func (m *RequestPasswordlessLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPasswordlessLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPasswordlessLoginResponse proto.InternalMessageInfo

type SubmitPasswordlessLoginRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *SubmitPasswordlessLoginRequest) Reset()      { *m = SubmitPasswordlessLoginRequest{} }
func (*SubmitPasswordlessLoginRequest) ProtoMessage() {}
func (*SubmitPasswordlessLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{8}
}
func (m *SubmitPasswordlessLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitPasswordlessLoginRequest.Unmarshal(m, b)
}
func (m *SubmitPasswordlessLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitPasswordlessLoginRequest.Marshal(b, m, deterministic)
}
func (m *SubmitPasswordlessLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitPasswordlessLoginRequest.Merge(m, src)
}
func (m *SubmitPasswordlessLoginRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitPasswordlessLoginRequest.Size(m)
}
func (m *SubmitPasswordlessLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitPasswordlessLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitPasswordlessLoginRequest proto.InternalMessageInfo

func (m *SubmitPasswordlessLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SubmitPasswordlessLoginResponse struct {
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token"`
}

func (m *SubmitPasswordlessLoginResponse) Reset()      { *m = SubmitPasswordlessLoginResponse{} }
func (*SubmitPasswordlessLoginResponse) ProtoMessage() {}
func (*SubmitPasswordlessLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{9}
}
func (m *SubmitPasswordlessLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitPasswordlessLoginResponse.Unmarshal(m, b)
}
func (m *SubmitPasswordlessLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitPasswordlessLoginResponse.Marshal(b, m, deterministic)
}
func (m *SubmitPasswordlessLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitPasswordlessLoginResponse.Merge(m, src)
}
func (m *SubmitPasswordlessLoginResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitPasswordlessLoginResponse.Size(m)
}
func (m *SubmitPasswordlessLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitPasswordlessLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitPasswordlessLoginResponse proto.InternalMessageInfo

func (m *SubmitPasswordlessLoginResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()      { *m = LoginRequest{} }
func (*LoginRequest) ProtoMessage() {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{10}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token"`
}

func (m *LoginResponse) Reset()      { *m = LoginResponse{} }
func (*LoginResponse) ProtoMessage() {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{11}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type LogoutRequest struct {
}

func (m *LogoutRequest) Reset()      { *m = LogoutRequest{} }
func (*LogoutRequest) ProtoMessage() {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{12}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()      { *m = LogoutResponse{} }
func (*LogoutResponse) ProtoMessage() {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{13}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type RefreshSessionRequest struct {
}

func (m *RefreshSessionRequest) Reset()      { *m = RefreshSessionRequest{} }
func (*RefreshSessionRequest) ProtoMessage() {}
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{14}
}
func (m *RefreshSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshSessionRequest.Unmarshal(m, b)
}
func (m *RefreshSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshSessionRequest.Marshal(b, m, deterministic)
}
func (m *RefreshSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshSessionRequest.Merge(m, src)
}
func (m *RefreshSessionRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshSessionRequest.Size(m)
}
func (m *RefreshSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshSessionRequest proto.InternalMessageInfo

type RefreshSessionResponse struct {
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token"`
}

func (m *RefreshSessionResponse) Reset()      { *m = RefreshSessionResponse{} }
func (*RefreshSessionResponse) ProtoMessage() {}
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{15}
}
func (m *RefreshSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshSessionResponse.Unmarshal(m, b)
}
func (m *RefreshSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshSessionResponse.Marshal(b, m, deterministic)
}
func (m *RefreshSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshSessionResponse.Merge(m, src)
}
func (m *RefreshSessionResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshSessionResponse.Size(m)
}
func (m *RefreshSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshSessionResponse proto.InternalMessageInfo

func (m *RefreshSessionResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type ChangePasswordRequest struct {
	Password        string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Token           string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	CurrentPassword string `protobuf:"bytes,3,opt,name=currentPassword,proto3" json:"currentPassword,omitempty"`
}

func (m *ChangePasswordRequest) Reset()      { *m = ChangePasswordRequest{} }
func (*ChangePasswordRequest) ProtoMessage() {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{16}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token"`
}

func (m *ChangePasswordResponse) Reset()      { *m = ChangePasswordResponse{} }
func (*ChangePasswordResponse) ProtoMessage() {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{17}
}
func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type HealthCheckRequest struct {
}

func (m *HealthCheckRequest) Reset()      { *m = HealthCheckRequest{} }
func (*HealthCheckRequest) ProtoMessage() {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{18}
}
func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	Http  bool `protobuf:"varint,1,opt,name=http,proto3" json:"http,omitempty"`
	Db    bool `protobuf:"varint,2,opt,name=db,proto3" json:"db,omitempty"`
	Redis bool `protobuf:"varint,3,opt,name=redis,proto3" json:"redis,omitempty"`
}

func (m *HealthCheckResponse) Reset()      { *m = HealthCheckResponse{} }
func (*HealthCheckResponse) ProtoMessage() {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40bfba985381dd1, []int{19}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetHttp() bool {
	if m != nil {
		return m.Http
	}
	return false
}

func (m *HealthCheckResponse) GetDb() bool {
	if m != nil {
		return m.Db
	}
	return false
}

func (m *HealthCheckResponse) GetRedis() bool {
	if m != nil {
		return m.Redis
	}
	return false
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "keratin.authn.SignupRequest")
	golang_proto.RegisterType((*SignupRequest)(nil), "keratin.authn.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "keratin.authn.SignupResponse")
	golang_proto.RegisterType((*SignupResponse)(nil), "keratin.authn.SignupResponse")
	proto.RegisterType((*IsUsernameAvailableRequest)(nil), "keratin.authn.IsUsernameAvailableRequest")
	golang_proto.RegisterType((*IsUsernameAvailableRequest)(nil), "keratin.authn.IsUsernameAvailableRequest")
	proto.RegisterType((*IsUsernameAvailableResponse)(nil), "keratin.authn.IsUsernameAvailableResponse")
	golang_proto.RegisterType((*IsUsernameAvailableResponse)(nil), "keratin.authn.IsUsernameAvailableResponse")
	proto.RegisterType((*PasswordResetRequest)(nil), "keratin.authn.PasswordResetRequest")
	golang_proto.RegisterType((*PasswordResetRequest)(nil), "keratin.authn.PasswordResetRequest")
	proto.RegisterType((*PasswordResetResponse)(nil), "keratin.authn.PasswordResetResponse")
	golang_proto.RegisterType((*PasswordResetResponse)(nil), "keratin.authn.PasswordResetResponse")
	proto.RegisterType((*RequestPasswordlessLoginRequest)(nil), "keratin.authn.RequestPasswordlessLoginRequest")
	golang_proto.RegisterType((*RequestPasswordlessLoginRequest)(nil), "keratin.authn.RequestPasswordlessLoginRequest")
	proto.RegisterType((*RequestPasswordlessLoginResponse)(nil), "keratin.authn.RequestPasswordlessLoginResponse")
	golang_proto.RegisterType((*RequestPasswordlessLoginResponse)(nil), "keratin.authn.RequestPasswordlessLoginResponse")
	proto.RegisterType((*SubmitPasswordlessLoginRequest)(nil), "keratin.authn.SubmitPasswordlessLoginRequest")
	golang_proto.RegisterType((*SubmitPasswordlessLoginRequest)(nil), "keratin.authn.SubmitPasswordlessLoginRequest")
	proto.RegisterType((*SubmitPasswordlessLoginResponse)(nil), "keratin.authn.SubmitPasswordlessLoginResponse")
	golang_proto.RegisterType((*SubmitPasswordlessLoginResponse)(nil), "keratin.authn.SubmitPasswordlessLoginResponse")
	proto.RegisterType((*LoginRequest)(nil), "keratin.authn.LoginRequest")
	golang_proto.RegisterType((*LoginRequest)(nil), "keratin.authn.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "keratin.authn.LoginResponse")
	golang_proto.RegisterType((*LoginResponse)(nil), "keratin.authn.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "keratin.authn.LogoutRequest")
	golang_proto.RegisterType((*LogoutRequest)(nil), "keratin.authn.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "keratin.authn.LogoutResponse")
	golang_proto.RegisterType((*LogoutResponse)(nil), "keratin.authn.LogoutResponse")
	proto.RegisterType((*RefreshSessionRequest)(nil), "keratin.authn.RefreshSessionRequest")
	golang_proto.RegisterType((*RefreshSessionRequest)(nil), "keratin.authn.RefreshSessionRequest")
	proto.RegisterType((*RefreshSessionResponse)(nil), "keratin.authn.RefreshSessionResponse")
	golang_proto.RegisterType((*RefreshSessionResponse)(nil), "keratin.authn.RefreshSessionResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "keratin.authn.ChangePasswordRequest")
	golang_proto.RegisterType((*ChangePasswordRequest)(nil), "keratin.authn.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "keratin.authn.ChangePasswordResponse")
	golang_proto.RegisterType((*ChangePasswordResponse)(nil), "keratin.authn.ChangePasswordResponse")
	proto.RegisterType((*HealthCheckRequest)(nil), "keratin.authn.HealthCheckRequest")
	golang_proto.RegisterType((*HealthCheckRequest)(nil), "keratin.authn.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "keratin.authn.HealthCheckResponse")
	golang_proto.RegisterType((*HealthCheckResponse)(nil), "keratin.authn.HealthCheckResponse")
}

func init() { proto.RegisterFile("authn.proto", fileDescriptor_b40bfba985381dd1) }
func init() { golang_proto.RegisterFile("authn.proto", fileDescriptor_b40bfba985381dd1) }

var fileDescriptor_b40bfba985381dd1 = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x4f, 0xe3, 0x46,
	0x18, 0x8e, 0x53, 0x08, 0xe1, 0x85, 0x7c, 0x74, 0x92, 0x40, 0x6a, 0xa8, 0x43, 0x5d, 0xaa, 0xd2,
	0x48, 0xc4, 0x52, 0x2a, 0x55, 0x14, 0xa9, 0x87, 0x80, 0xd4, 0x2f, 0x55, 0x2d, 0x72, 0x5a, 0x21,
	0xb5, 0x87, 0xca, 0x76, 0x06, 0xdb, 0x22, 0x78, 0xb2, 0x1e, 0x1b, 0xa4, 0x3d, 0xad, 0xf6, 0xb6,
	0xb7, 0xd5, 0xb2, 0x3f, 0x62, 0x7f, 0xc2, 0x1e, 0x77, 0xff, 0xc1, 0x4a, 0x7b, 0xe1, 0x84, 0x04,
	0xd9, 0x13, 0xbf, 0x80, 0xe3, 0x2a, 0xe3, 0xb1, 0x49, 0x1c, 0x27, 0x84, 0x3d, 0xc5, 0xf3, 0x7e,
	0x3d, 0xcf, 0xbc, 0xef, 0x3b, 0x8f, 0x02, 0x4b, 0x9a, 0xef, 0x59, 0x4e, 0xa3, 0xe7, 0x12, 0x8f,
	0xa0, 0xdc, 0x31, 0x76, 0x35, 0xcf, 0x76, 0x1a, 0xcc, 0x28, 0x6e, 0x9b, 0xb6, 0x67, 0xf9, 0x7a,
	0xc3, 0x20, 0x27, 0x8a, 0x49, 0x4c, 0xa2, 0xb0, 0x28, 0xdd, 0x3f, 0x62, 0x27, 0x76, 0x60, 0x5f,
	0x41, 0xb6, 0xb8, 0x6e, 0x12, 0x62, 0x76, 0xb1, 0xa2, 0xf5, 0x6c, 0x45, 0x73, 0x1c, 0xe2, 0x69,
	0x9e, 0x4d, 0x1c, 0x1a, 0x78, 0xe5, 0x5f, 0x20, 0xd7, 0xb6, 0x4d, 0xc7, 0xef, 0xa9, 0xf8, 0x91,
	0x8f, 0xa9, 0x87, 0x44, 0xc8, 0xfa, 0x14, 0xbb, 0x8e, 0x76, 0x82, 0xab, 0xc2, 0x86, 0xb0, 0xb5,
	0xa8, 0x46, 0xe7, 0x81, 0xaf, 0xa7, 0x51, 0x7a, 0x46, 0xdc, 0x4e, 0x35, 0x1d, 0xf8, 0xc2, 0xb3,
	0xfc, 0x23, 0xe4, 0xc3, 0x42, 0xb4, 0x47, 0x1c, 0x8a, 0xd1, 0xb7, 0x90, 0xb5, 0x3b, 0xff, 0x7b,
	0xe4, 0x18, 0x3b, 0x41, 0xa5, 0xbd, 0xe5, 0x9b, 0xcb, 0x5a, 0x64, 0x53, 0x17, 0xec, 0xce, 0xdf,
	0x83, 0x0f, 0x79, 0x07, 0xc4, 0xdf, 0xe8, 0x3f, 0x1c, 0xa4, 0x75, 0xaa, 0xd9, 0x5d, 0x4d, 0xef,
	0xe2, 0x19, 0x08, 0xc9, 0x2d, 0x58, 0x4b, 0xcc, 0xe4, 0x0c, 0x64, 0xc8, 0xb8, 0x98, 0xfa, 0x5d,
	0x8f, 0x25, 0x66, 0xf7, 0xe0, 0xe6, 0xb2, 0xc6, 0x2d, 0x2a, 0xff, 0x95, 0x9b, 0x50, 0x3e, 0xe0,
	0x77, 0x50, 0x31, 0xc5, 0xde, 0x2c, 0xb0, 0xab, 0x50, 0x89, 0xe5, 0x04, 0x80, 0xf2, 0x4f, 0x50,
	0xe3, 0xf9, 0xa1, 0xbf, 0x8b, 0x29, 0xfd, 0x83, 0x98, 0xb6, 0x33, 0x4b, 0x5d, 0x19, 0x36, 0x26,
	0xa7, 0x73, 0x88, 0x1f, 0x40, 0x6a, 0xfb, 0xfa, 0x89, 0x3d, 0x19, 0xa1, 0x0c, 0xf3, 0x43, 0x4d,
	0x57, 0x83, 0x83, 0xfc, 0x3b, 0xd4, 0x26, 0xe6, 0x3d, 0x74, 0x60, 0x3f, 0xc3, 0xf2, 0xac, 0x77,
	0x9a, 0xba, 0x33, 0x3b, 0x90, 0xfb, 0x44, 0x06, 0x05, 0x96, 0x49, 0xfc, 0x70, 0x5c, 0x72, 0x11,
	0xf2, 0xa1, 0x81, 0x37, 0x6a, 0x15, 0x2a, 0x2a, 0x3e, 0x72, 0x31, 0xb5, 0xda, 0x98, 0x52, 0x9b,
	0x84, 0x6c, 0xe5, 0x16, 0xac, 0xc4, 0x1d, 0x0f, 0x85, 0xa7, 0x50, 0xd9, 0xb7, 0x34, 0xc7, 0xc4,
	0x77, 0x6b, 0x10, 0x75, 0x22, 0xba, 0xad, 0x30, 0x7a, 0xdb, 0xbb, 0xb9, 0xa4, 0x87, 0xe6, 0x82,
	0xb6, 0xa0, 0x60, 0xf8, 0xae, 0x8b, 0x9d, 0x68, 0x30, 0xd5, 0xcf, 0x98, 0x3f, 0x6e, 0x1e, 0xf0,
	0x8e, 0x83, 0x3e, 0x94, 0x77, 0x19, 0xd0, 0xaf, 0x58, 0xeb, 0x7a, 0xd6, 0xbe, 0x85, 0x8d, 0xe3,
	0xb0, 0x21, 0x7f, 0x41, 0x69, 0xc4, 0xca, 0xab, 0x22, 0x98, 0xb3, 0x3c, 0xaf, 0x17, 0xbc, 0x1d,
	0x95, 0x7d, 0xa3, 0x3c, 0xa4, 0x3b, 0x3a, 0xbb, 0x40, 0x56, 0x4d, 0x77, 0xf4, 0xc1, 0x9d, 0x5c,
	0xdc, 0xb1, 0x29, 0xe3, 0x9c, 0x55, 0x83, 0x43, 0xf3, 0x56, 0x08, 0x55, 0xa5, 0x8d, 0xdd, 0x53,
	0xdb, 0xc0, 0xe8, 0x3f, 0xc8, 0x04, 0x06, 0xb4, 0xde, 0x18, 0x51, 0xb3, 0xc6, 0x88, 0xfa, 0x88,
	0x5f, 0x4e, 0xf0, 0xf2, 0x99, 0x96, 0x9f, 0xbe, 0xff, 0x70, 0x9e, 0xce, 0xcb, 0x8b, 0x8a, 0x66,
	0x18, 0xc4, 0x77, 0x3c, 0xba, 0x2b, 0xd4, 0xd1, 0x33, 0x01, 0x4a, 0x09, 0x32, 0x80, 0xbe, 0x8b,
	0x15, 0x9b, 0x2c, 0x32, 0x62, 0x7d, 0x96, 0x50, 0x4e, 0x62, 0x8d, 0x91, 0xa8, 0xa0, 0x52, 0x44,
	0x42, 0xd1, 0xc2, 0xa0, 0xe6, 0x0b, 0x21, 0xa6, 0x27, 0x61, 0x07, 0x1e, 0x43, 0x39, 0xf6, 0xb6,
	0x99, 0x1b, 0x7d, 0x1d, 0x43, 0x4e, 0x12, 0x23, 0x71, 0x73, 0x7a, 0x50, 0xb8, 0xf1, 0x8c, 0xd8,
	0xe7, 0xa8, 0xa0, 0x84, 0x3b, 0xa7, 0xb8, 0x83, 0x80, 0xe6, 0xdb, 0x34, 0x94, 0x86, 0x9f, 0x7d,
	0xc8, 0xe9, 0x5c, 0x80, 0xea, 0x24, 0xc1, 0x41, 0x8d, 0x18, 0xe6, 0x3d, 0xc2, 0x26, 0x2a, 0x33,
	0xc7, 0x73, 0xba, 0x2b, 0x8c, 0x6e, 0x11, 0xe5, 0x15, 0x1a, 0xbc, 0x43, 0x25, 0x78, 0x11, 0xe7,
	0x02, 0xac, 0x4e, 0x90, 0x2a, 0xb4, 0x1d, 0xdf, 0x8f, 0xa9, 0x52, 0x28, 0x36, 0x66, 0x0d, 0xe7,
	0x94, 0xbe, 0x60, 0x94, 0x4a, 0x72, 0x8c, 0xd2, 0xae, 0x50, 0x6f, 0xbe, 0x9c, 0x83, 0xa5, 0x03,
	0x5f, 0xef, 0xda, 0x46, 0xcb, 0xf7, 0xac, 0x3f, 0xd1, 0x21, 0xcc, 0x07, 0x94, 0xd6, 0x62, 0x18,
	0x23, 0x04, 0xd6, 0x93, 0x9d, 0x1c, 0xae, 0xc4, 0xe0, 0x72, 0x72, 0x36, 0x84, 0x1b, 0x6c, 0xf3,
	0x21, 0x64, 0x02, 0x25, 0x43, 0x09, 0xc9, 0x77, 0x8a, 0x37, 0xf6, 0x54, 0x62, 0xf2, 0x57, 0x64,
	0xb5, 0xa1, 0x1e, 0xd5, 0x46, 0x67, 0x90, 0x1f, 0xd5, 0x3d, 0xb4, 0x39, 0x36, 0xb2, 0x04, 0xbd,
	0x14, 0xbf, 0xb9, 0x27, 0x8a, 0x03, 0x56, 0x19, 0x20, 0x42, 0xc5, 0xa8, 0x77, 0x6e, 0x10, 0x88,
	0x28, 0xe4, 0x47, 0x85, 0x6b, 0x0c, 0x38, 0x51, 0x4c, 0xc7, 0x80, 0x93, 0xd5, 0x6f, 0x48, 0x14,
	0xc2, 0xb5, 0x1f, 0xb4, 0x11, 0xc3, 0xd2, 0x90, 0xa8, 0xa1, 0xaf, 0x62, 0xb5, 0xc6, 0x65, 0x50,
	0x94, 0xa7, 0x85, 0x70, 0xac, 0x02, 0xc3, 0x5a, 0x44, 0x0b, 0x8a, 0xc5, 0xbc, 0x7b, 0xf5, 0x8b,
	0x2b, 0x29, 0x75, 0x7b, 0x25, 0x09, 0x4f, 0xae, 0x25, 0xe1, 0xd5, 0xb5, 0x24, 0xbc, 0xbe, 0x96,
	0x84, 0xe7, 0x7d, 0x29, 0xf5, 0xa6, 0x2f, 0x09, 0xef, 0xfa, 0x52, 0xea, 0xa2, 0x2f, 0xa5, 0xfe,
	0x9d, 0x33, 0xdd, 0x9e, 0xa1, 0x67, 0xd8, 0x5f, 0xae, 0xef, 0x3f, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xaf, 0xbe, 0x3d, 0x1c, 0xdd, 0x09, 0x00, 0x00,
}

func (this *SignupRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SignupRequest)
	if !ok {
		that2, ok := that.(SignupRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	if this.Password != that1.Password {
		return false
	}
	return true
}
func (this *SignupResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SignupResponse)
	if !ok {
		that2, ok := that.(SignupResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IdToken != that1.IdToken {
		return false
	}
	return true
}
func (this *IsUsernameAvailableRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IsUsernameAvailableRequest)
	if !ok {
		that2, ok := that.(IsUsernameAvailableRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	return true
}
func (this *IsUsernameAvailableResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IsUsernameAvailableResponse)
	if !ok {
		that2, ok := that.(IsUsernameAvailableResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Result != that1.Result {
		return false
	}
	return true
}
func (this *PasswordResetRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PasswordResetRequest)
	if !ok {
		that2, ok := that.(PasswordResetRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	return true
}
func (this *PasswordResetResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PasswordResetResponse)
	if !ok {
		that2, ok := that.(PasswordResetResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *RequestPasswordlessLoginRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestPasswordlessLoginRequest)
	if !ok {
		that2, ok := that.(RequestPasswordlessLoginRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	return true
}
func (this *RequestPasswordlessLoginResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestPasswordlessLoginResponse)
	if !ok {
		that2, ok := that.(RequestPasswordlessLoginResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *SubmitPasswordlessLoginRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitPasswordlessLoginRequest)
	if !ok {
		that2, ok := that.(SubmitPasswordlessLoginRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Token != that1.Token {
		return false
	}
	return true
}
func (this *SubmitPasswordlessLoginResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitPasswordlessLoginResponse)
	if !ok {
		that2, ok := that.(SubmitPasswordlessLoginResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IdToken != that1.IdToken {
		return false
	}
	return true
}
func (this *LoginRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginRequest)
	if !ok {
		that2, ok := that.(LoginRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Username != that1.Username {
		return false
	}
	if this.Password != that1.Password {
		return false
	}
	return true
}
func (this *LoginResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LoginResponse)
	if !ok {
		that2, ok := that.(LoginResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IdToken != that1.IdToken {
		return false
	}
	return true
}
func (this *LogoutRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LogoutRequest)
	if !ok {
		that2, ok := that.(LogoutRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *LogoutResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LogoutResponse)
	if !ok {
		that2, ok := that.(LogoutResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *RefreshSessionRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RefreshSessionRequest)
	if !ok {
		that2, ok := that.(RefreshSessionRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *RefreshSessionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RefreshSessionResponse)
	if !ok {
		that2, ok := that.(RefreshSessionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IdToken != that1.IdToken {
		return false
	}
	return true
}
func (this *ChangePasswordRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChangePasswordRequest)
	if !ok {
		that2, ok := that.(ChangePasswordRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Password != that1.Password {
		return false
	}
	if this.Token != that1.Token {
		return false
	}
	if this.CurrentPassword != that1.CurrentPassword {
		return false
	}
	return true
}
func (this *ChangePasswordResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChangePasswordResponse)
	if !ok {
		that2, ok := that.(ChangePasswordResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IdToken != that1.IdToken {
		return false
	}
	return true
}
func (this *HealthCheckRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckRequest)
	if !ok {
		that2, ok := that.(HealthCheckRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *HealthCheckResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckResponse)
	if !ok {
		that2, ok := that.(HealthCheckResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Http != that1.Http {
		return false
	}
	if this.Db != that1.Db {
		return false
	}
	if this.Redis != that1.Redis {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignupServiceClient is the client API for SignupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignupServiceClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	IsUsernameAvailable(ctx context.Context, in *IsUsernameAvailableRequest, opts ...grpc.CallOption) (*IsUsernameAvailableResponse, error)
}

type signupServiceClient struct {
	cc *grpc.ClientConn
}

func NewSignupServiceClient(cc *grpc.ClientConn) SignupServiceClient {
	return &signupServiceClient{cc}
}

func (c *signupServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.SignupService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signupServiceClient) IsUsernameAvailable(ctx context.Context, in *IsUsernameAvailableRequest, opts ...grpc.CallOption) (*IsUsernameAvailableResponse, error) {
	out := new(IsUsernameAvailableResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.SignupService/IsUsernameAvailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignupServiceServer is the server API for SignupService service.
type SignupServiceServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	IsUsernameAvailable(context.Context, *IsUsernameAvailableRequest) (*IsUsernameAvailableResponse, error)
}

// UnimplementedSignupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignupServiceServer struct {
}

func (*UnimplementedSignupServiceServer) Signup(ctx context.Context, req *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedSignupServiceServer) IsUsernameAvailable(ctx context.Context, req *IsUsernameAvailableRequest) (*IsUsernameAvailableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUsernameAvailable not implemented")
}

func RegisterSignupServiceServer(s *grpc.Server, srv SignupServiceServer) {
	s.RegisterService(&_SignupService_serviceDesc, srv)
}

func _SignupService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.SignupService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignupService_IsUsernameAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUsernameAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignupServiceServer).IsUsernameAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.SignupService/IsUsernameAvailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignupServiceServer).IsUsernameAvailable(ctx, req.(*IsUsernameAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keratin.authn.SignupService",
	HandlerType: (*SignupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _SignupService_Signup_Handler,
		},
		{
			MethodName: "IsUsernameAvailable",
			Handler:    _SignupService_IsUsernameAvailable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authn.proto",
}

// PasswordResetServiceClient is the client API for PasswordResetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PasswordResetServiceClient interface {
	RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*PasswordResetResponse, error)
}

type passwordResetServiceClient struct {
	cc *grpc.ClientConn
}

func NewPasswordResetServiceClient(cc *grpc.ClientConn) PasswordResetServiceClient {
	return &passwordResetServiceClient{cc}
}

func (c *passwordResetServiceClient) RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*PasswordResetResponse, error) {
	out := new(PasswordResetResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PasswordResetService/RequestPasswordReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordResetServiceServer is the server API for PasswordResetService service.
type PasswordResetServiceServer interface {
	RequestPasswordReset(context.Context, *PasswordResetRequest) (*PasswordResetResponse, error)
}

// UnimplementedPasswordResetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPasswordResetServiceServer struct {
}

func (*UnimplementedPasswordResetServiceServer) RequestPasswordReset(ctx context.Context, req *PasswordResetRequest) (*PasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPasswordReset not implemented")
}

func RegisterPasswordResetServiceServer(s *grpc.Server, srv PasswordResetServiceServer) {
	s.RegisterService(&_PasswordResetService_serviceDesc, srv)
}

func _PasswordResetService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordResetServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PasswordResetService/RequestPasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordResetServiceServer).RequestPasswordReset(ctx, req.(*PasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PasswordResetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keratin.authn.PasswordResetService",
	HandlerType: (*PasswordResetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPasswordReset",
			Handler:    _PasswordResetService_RequestPasswordReset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authn.proto",
}

// PasswordlessServiceClient is the client API for PasswordlessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PasswordlessServiceClient interface {
	RequestPasswordlessLogin(ctx context.Context, in *RequestPasswordlessLoginRequest, opts ...grpc.CallOption) (*RequestPasswordlessLoginResponse, error)
	SubmitPasswordlessLogin(ctx context.Context, in *SubmitPasswordlessLoginRequest, opts ...grpc.CallOption) (*SubmitPasswordlessLoginResponse, error)
}

type passwordlessServiceClient struct {
	cc *grpc.ClientConn
}

func NewPasswordlessServiceClient(cc *grpc.ClientConn) PasswordlessServiceClient {
	return &passwordlessServiceClient{cc}
}

func (c *passwordlessServiceClient) RequestPasswordlessLogin(ctx context.Context, in *RequestPasswordlessLoginRequest, opts ...grpc.CallOption) (*RequestPasswordlessLoginResponse, error) {
	out := new(RequestPasswordlessLoginResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PasswordlessService/RequestPasswordlessLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordlessServiceClient) SubmitPasswordlessLogin(ctx context.Context, in *SubmitPasswordlessLoginRequest, opts ...grpc.CallOption) (*SubmitPasswordlessLoginResponse, error) {
	out := new(SubmitPasswordlessLoginResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PasswordlessService/SubmitPasswordlessLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordlessServiceServer is the server API for PasswordlessService service.
type PasswordlessServiceServer interface {
	RequestPasswordlessLogin(context.Context, *RequestPasswordlessLoginRequest) (*RequestPasswordlessLoginResponse, error)
	SubmitPasswordlessLogin(context.Context, *SubmitPasswordlessLoginRequest) (*SubmitPasswordlessLoginResponse, error)
}

// UnimplementedPasswordlessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPasswordlessServiceServer struct {
}

func (*UnimplementedPasswordlessServiceServer) RequestPasswordlessLogin(ctx context.Context, req *RequestPasswordlessLoginRequest) (*RequestPasswordlessLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPasswordlessLogin not implemented")
}
func (*UnimplementedPasswordlessServiceServer) SubmitPasswordlessLogin(ctx context.Context, req *SubmitPasswordlessLoginRequest) (*SubmitPasswordlessLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPasswordlessLogin not implemented")
}

func RegisterPasswordlessServiceServer(s *grpc.Server, srv PasswordlessServiceServer) {
	s.RegisterService(&_PasswordlessService_serviceDesc, srv)
}

func _PasswordlessService_RequestPasswordlessLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPasswordlessLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordlessServiceServer).RequestPasswordlessLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PasswordlessService/RequestPasswordlessLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordlessServiceServer).RequestPasswordlessLogin(ctx, req.(*RequestPasswordlessLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordlessService_SubmitPasswordlessLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPasswordlessLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordlessServiceServer).SubmitPasswordlessLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PasswordlessService/SubmitPasswordlessLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordlessServiceServer).SubmitPasswordlessLogin(ctx, req.(*SubmitPasswordlessLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PasswordlessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keratin.authn.PasswordlessService",
	HandlerType: (*PasswordlessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPasswordlessLogin",
			Handler:    _PasswordlessService_RequestPasswordlessLogin_Handler,
		},
		{
			MethodName: "SubmitPasswordlessLogin",
			Handler:    _PasswordlessService_SubmitPasswordlessLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authn.proto",
}

// PublicAuthNClient is the client API for PublicAuthN service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublicAuthNClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type publicAuthNClient struct {
	cc *grpc.ClientConn
}

func NewPublicAuthNClient(cc *grpc.ClientConn) PublicAuthNClient {
	return &publicAuthNClient{cc}
}

func (c *publicAuthNClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PublicAuthN/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAuthNClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PublicAuthN/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAuthNClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error) {
	out := new(RefreshSessionResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PublicAuthN/RefreshSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAuthNClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PublicAuthN/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAuthNClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/keratin.authn.PublicAuthN/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicAuthNServer is the server API for PublicAuthN service.
type PublicAuthNServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedPublicAuthNServer can be embedded to have forward compatible implementations.
type UnimplementedPublicAuthNServer struct {
}

func (*UnimplementedPublicAuthNServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedPublicAuthNServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedPublicAuthNServer) RefreshSession(ctx context.Context, req *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}
func (*UnimplementedPublicAuthNServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedPublicAuthNServer) HealthCheck(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

func RegisterPublicAuthNServer(s *grpc.Server, srv PublicAuthNServer) {
	s.RegisterService(&_PublicAuthN_serviceDesc, srv)
}

func _PublicAuthN_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAuthNServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PublicAuthN/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAuthNServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAuthN_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAuthNServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PublicAuthN/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAuthNServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAuthN_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAuthNServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PublicAuthN/RefreshSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAuthNServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAuthN_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAuthNServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PublicAuthN/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAuthNServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAuthN_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAuthNServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keratin.authn.PublicAuthN/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAuthNServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicAuthN_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keratin.authn.PublicAuthN",
	HandlerType: (*PublicAuthNServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _PublicAuthN_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PublicAuthN_Logout_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _PublicAuthN_RefreshSession_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _PublicAuthN_ChangePassword_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PublicAuthN_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authn.proto",
}

func NewPopulatedSignupRequest(r randyAuthn, easy bool) *SignupRequest {
	this := &SignupRequest{}
	this.Username = string(randStringAuthn(r))
	this.Password = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSignupResponse(r randyAuthn, easy bool) *SignupResponse {
	this := &SignupResponse{}
	this.IdToken = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedIsUsernameAvailableRequest(r randyAuthn, easy bool) *IsUsernameAvailableRequest {
	this := &IsUsernameAvailableRequest{}
	this.Username = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedIsUsernameAvailableResponse(r randyAuthn, easy bool) *IsUsernameAvailableResponse {
	this := &IsUsernameAvailableResponse{}
	this.Result = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPasswordResetRequest(r randyAuthn, easy bool) *PasswordResetRequest {
	this := &PasswordResetRequest{}
	this.Username = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPasswordResetResponse(r randyAuthn, easy bool) *PasswordResetResponse {
	this := &PasswordResetResponse{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRequestPasswordlessLoginRequest(r randyAuthn, easy bool) *RequestPasswordlessLoginRequest {
	this := &RequestPasswordlessLoginRequest{}
	this.Username = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRequestPasswordlessLoginResponse(r randyAuthn, easy bool) *RequestPasswordlessLoginResponse {
	this := &RequestPasswordlessLoginResponse{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSubmitPasswordlessLoginRequest(r randyAuthn, easy bool) *SubmitPasswordlessLoginRequest {
	this := &SubmitPasswordlessLoginRequest{}
	this.Token = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSubmitPasswordlessLoginResponse(r randyAuthn, easy bool) *SubmitPasswordlessLoginResponse {
	this := &SubmitPasswordlessLoginResponse{}
	this.IdToken = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLoginRequest(r randyAuthn, easy bool) *LoginRequest {
	this := &LoginRequest{}
	this.Username = string(randStringAuthn(r))
	this.Password = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLoginResponse(r randyAuthn, easy bool) *LoginResponse {
	this := &LoginResponse{}
	this.IdToken = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLogoutRequest(r randyAuthn, easy bool) *LogoutRequest {
	this := &LogoutRequest{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedLogoutResponse(r randyAuthn, easy bool) *LogoutResponse {
	this := &LogoutResponse{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRefreshSessionRequest(r randyAuthn, easy bool) *RefreshSessionRequest {
	this := &RefreshSessionRequest{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedRefreshSessionResponse(r randyAuthn, easy bool) *RefreshSessionResponse {
	this := &RefreshSessionResponse{}
	this.IdToken = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedChangePasswordRequest(r randyAuthn, easy bool) *ChangePasswordRequest {
	this := &ChangePasswordRequest{}
	this.Password = string(randStringAuthn(r))
	this.Token = string(randStringAuthn(r))
	this.CurrentPassword = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedChangePasswordResponse(r randyAuthn, easy bool) *ChangePasswordResponse {
	this := &ChangePasswordResponse{}
	this.IdToken = string(randStringAuthn(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedHealthCheckRequest(r randyAuthn, easy bool) *HealthCheckRequest {
	this := &HealthCheckRequest{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedHealthCheckResponse(r randyAuthn, easy bool) *HealthCheckResponse {
	this := &HealthCheckResponse{}
	this.Http = bool(bool(r.Intn(2) == 0))
	this.Db = bool(bool(r.Intn(2) == 0))
	this.Redis = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyAuthn interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneAuthn(r randyAuthn) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringAuthn(r randyAuthn) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneAuthn(r)
	}
	return string(tmps)
}
func randUnrecognizedAuthn(r randyAuthn, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldAuthn(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldAuthn(dAtA []byte, r randyAuthn, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateAuthn(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateAuthn(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateAuthn(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateAuthn(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateAuthn(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateAuthn(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateAuthn(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (this *SignupRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SignupRequest{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`Password:` + fmt.Sprintf("%v", this.Password) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SignupResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SignupResponse{`,
		`IdToken:` + fmt.Sprintf("%v", this.IdToken) + `,`,
		`}`,
	}, "")
	return s
}
func (this *IsUsernameAvailableRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&IsUsernameAvailableRequest{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`}`,
	}, "")
	return s
}
func (this *IsUsernameAvailableResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&IsUsernameAvailableResponse{`,
		`Result:` + fmt.Sprintf("%v", this.Result) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PasswordResetRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PasswordResetRequest{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PasswordResetResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PasswordResetResponse{`,
		`}`,
	}, "")
	return s
}
func (this *RequestPasswordlessLoginRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestPasswordlessLoginRequest{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestPasswordlessLoginResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestPasswordlessLoginResponse{`,
		`}`,
	}, "")
	return s
}
func (this *SubmitPasswordlessLoginRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitPasswordlessLoginRequest{`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitPasswordlessLoginResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitPasswordlessLoginResponse{`,
		`IdToken:` + fmt.Sprintf("%v", this.IdToken) + `,`,
		`}`,
	}, "")
	return s
}
func (this *LoginRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LoginRequest{`,
		`Username:` + fmt.Sprintf("%v", this.Username) + `,`,
		`Password:` + fmt.Sprintf("%v", this.Password) + `,`,
		`}`,
	}, "")
	return s
}
func (this *LoginResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LoginResponse{`,
		`IdToken:` + fmt.Sprintf("%v", this.IdToken) + `,`,
		`}`,
	}, "")
	return s
}
func (this *LogoutRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LogoutRequest{`,
		`}`,
	}, "")
	return s
}
func (this *LogoutResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LogoutResponse{`,
		`}`,
	}, "")
	return s
}
func (this *RefreshSessionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RefreshSessionRequest{`,
		`}`,
	}, "")
	return s
}
func (this *RefreshSessionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RefreshSessionResponse{`,
		`IdToken:` + fmt.Sprintf("%v", this.IdToken) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ChangePasswordRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ChangePasswordRequest{`,
		`Password:` + fmt.Sprintf("%v", this.Password) + `,`,
		`Token:` + fmt.Sprintf("%v", this.Token) + `,`,
		`CurrentPassword:` + fmt.Sprintf("%v", this.CurrentPassword) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ChangePasswordResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ChangePasswordResponse{`,
		`IdToken:` + fmt.Sprintf("%v", this.IdToken) + `,`,
		`}`,
	}, "")
	return s
}
func (this *HealthCheckRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HealthCheckRequest{`,
		`}`,
	}, "")
	return s
}
func (this *HealthCheckResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&HealthCheckResponse{`,
		`Http:` + fmt.Sprintf("%v", this.Http) + `,`,
		`Db:` + fmt.Sprintf("%v", this.Db) + `,`,
		`Redis:` + fmt.Sprintf("%v", this.Redis) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAuthn(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
